services:

  configserver:
    image: "kapoormayank/configserver:s8"
    container_name: configserver_ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail http://localhost:8071/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-based-config


  eurekaserver:
    image: "kapoormayank/eurekaserver:s8"
    container_name: eurekaserver_ms
    ports:
      - "8070:8070"
    healthcheck:
      test: "curl --fail http://localhost:8070/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-based-config
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"

  accounts:
      image: "kapoormayank/accounts:s8"
      container_name: accounts_ms
      ports:
        - "8080:8080"
      environment:
        SPRING_APPLICATION_NAME: "accounts"
      extends:
        file: common-config.yml
        service: microservice-configserver-config


  loans:
      image: "kapoormayank/loans:s8"
      container_name: loans_ms
      ports:
        - "8090:8090"
      environment:
        SPRING_APPLICATION_NAME: "loans"
      extends:
        file: common-config.yml
        service: microservice-configserver-config


  cards:
      image: "kapoormayank/cards:s8"
      container_name: cards_ms
      ports:
        - "9000:9000"
      environment:
        SPRING_APPLICATION_NAME: "cards"
      extends:
        file: common-config.yml
        service: microservice-configserver-config

networks:
  kapoornetwork:
    driver: "bridge"