services:
  network-deploy-service:
    networks:
      - kapoornetwork

  microservice-db-config:
    extends:
      service: network-deploy-service
    image: mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      interval: 10s
      retries: 10
      start_interval: 10s
    environment:
      MYSQL_ROOT_PASSWORD: "root"

  microservice-based-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: "700m"

  microservice-configserver-config:
    extends:
      service: microservice-based-config
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: qa
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"