services:
    accounts:
      image: "kapoormayank/accounts:s4"
      container_name: accounts_ms
      ports:
        - "8080:8080"
      deploy:
        resources:
          limits:
            memory: "700m"
      networks:
        - kapoornetwork

    loans:
      image: "kapoormayank/loans:s4"
      container_name: loans_ms
      ports:
        - "8090:8090"
      deploy:
        resources:
          limits:
            memory: "700m"
      networks:
        - kapoornetwork

    cards:
      image: "kapoormayank/cards:s4"
      container_name: cards_ms
      ports:
        - "9000:9000"
      deploy:
        resources:
          limits:
            memory: "700m"
      networks:
        - kapoornetwork

networks:
  kapoornetwork:
    driver: "bridge"